name: samacharpatra
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.5
  go_router: ^14.8.1
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  shared_preferences: ^2.5.3
  http: ^1.3.0
  custom_refresh_indicator: ^4.0.1
  url_launcher: ^6.3.1
  sqflite: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  flutter_image_compress: ^2.4.0
  intl: ^0.20.2
  connectivity_plus: ^6.1.3
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  smooth_page_indicator: ^1.2.1
  lottie: ^3.3.1
  flutter_dotenv: ^5.2.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/icons/ic_launcher.png'
  adaptive_icon_foreground: 'assets/icons/ic_launcher.png'
  adaptive_icon_background: "#000000"

flutter_native_splash:
  android: true
  ios: true
  color: "#ffffff"
  color_dark: "#000000"
  image: 'assets/icons/ic_launcher.png'
  image_dark: 'assets/icons/ic_launcher.png'
  fullscreen: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/files/
    - assets/animations/
    - .env

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto-regular.ttf
#          style: regular
